server:
  port: 8080

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: AUTH-SERVICE
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/v1/auth/**
          # filters:
          #   - RewritePath=/api/v1/auth/?(?<segment>.*), /auth/${segment}

        - id: AUTH-SERVICE
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/v1/internal/workspaces/**, /api/v1//internal/profiles/**, /api/v1/internal/memberships/**
          # filters:
          #   - RewritePath=/api/v1/auth/?(?<segment>.*), /auth/${segment}

        - id: BFF-SERVICE-APP
          uri: lb://BFF-SERVICE
          predicates:
            - Path=/api/v1/app/**
          # filters:
          #   - RewritePath=/api/v1/app/?(?<segment>.*), /${segment}

        - id: BFF-SERVICE-PUBLIC
          uri: lb://BFF-SERVICE
          predicates:
            - Path=/api/v1/public/**
          # filters:
          #   - RewritePath=/api/v1/public/?(?<segment>.*), /${segment}

        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v1/users/**
          # filters:
          #   - RewritePath=/api/v1/(?<segment>.*), /${segment}

        - id: USER-PORTFOLIO-SERVICE
          uri: lb://USER-PORTFOLIO-SERVICE
          predicates:
            - Path=/api/v1/user-info/**
          # filters:
          #   - RewritePath=/api/v1/(?<segment>.*), /${segment}

        - id: BUSINESS-SERVICE
          uri: lb://BUSINESS-SERVICE
          predicates:
            - Path=/api/v1/business/**,/api/v1/businesses/**
          # filters:
          #   - RewritePath=/api/v1/(?<segment>.*), /${segment}

        - id: POST-SERVICE
          uri: lb://POST-SERVICE
          predicates:
            - Path=/api/v1/posts/**
          # filters:
          #   - RewritePath=/api/v1/(?<segment>.*), /${segment}

        - id: PRODUCT-SERVICE
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/api/v1/products/**,/api/v1/drafts/**,/api/v1/files/**
          # filters:
          #   - RewritePath=/api/v1/(?<segment>.*), /${segment}

        - id: MEDIA-SERVICE
          uri: lb://MEDIA-SERVICE
          predicates:
            - Path=/api/v1/media/**
          # filters:
          #   - RewritePath=/api/v1/(?<segment>.*), /${segment}

        - id: SOCIAL-GRAPH-SERVICE
          uri: lb://SOCIAL-GRAPH-SERVICE
          predicates:
            - Path=/api/v1/social-graph/**
          # filters:
          #   - RewritePath=/api/v1/(?<segment>.*), /${segment}

        - id: CHAT-SERVICE
          uri: lb://CHAT-SERVICE
          predicates:
            - Path=/api/v1/chats/**
          # filters:
          #   - RewritePath=/api/v1/(?<segment>.*), /${segment}

        - id: NOTIFICATION-SERVICE
          uri: lb://NOTIFICATION-SERVICE
          predicates:
            - Path=/api/v1/notifications/**
          # filters:
          #   - RewritePath=/api/v1/(?<segment>.*), /${segment}

eureka:
  client:
    enabled: true
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    prefer-ip-address: true

jwt:
  secret: "mysecretkey123456789012345678901234"
  access-token-ttl: "900000"
  refresh-token-ttl: "604800000"

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    com.ahad.gateway.filter: DEBUG

info:
  app:
    name: API-GATEWAY
    version: 1.0.0
