server:
  port: 8080

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:

        # AUTH-SERVICE (PUBLIC)
        - id: AUTH-SERVICE
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**,/authenticate

        # USER-SERVICE (PROTECTED)
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**, /addresses/**

        # SHOP-SERVICE (PROTECTED)
        - id: BUSINESS-SERVICE
          uri: lb://BUSINESS-SERVICE
          predicates:
            - Path=/business/**
            
        # POST-SERVICE (BOTH)
        - id: POST-SERVICE
          uri: lb://POST-SERVICE
          predicates:
            - Path=/posts/**
            
       # Internal calls bypass
        - id: PROFILE-SERVICE-INTERNAL
          uri: lb://PROFILE-SERVICE
          predicates:
            - Path=/user-info/internal/**
            # internal auth skip karna
        
        # Public / user endpoints normal
        - id: PROFILE-SERVICE
          uri: lb://PROFILE-SERVICE
          predicates:
            - Path=/user-info/**, !/user-info/internal/**


        # Media-SERVICE (BOTH)
        - id: MEDIA-SERVICE
          uri: lb://MEDIA-SERVICE
          predicates:
            - Path=/media/**

             
# JWT Configuration
jwt:
  secret: "mysecretkey123456789012345678901234"
  access-token-ttl: "900000"      # 15 min (ms)
  refresh-token-ttl: "604800000"  # 7 days (ms)

# Management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

# Logging
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    com.ahad.gateway.filter: DEBUG

# App info
info:
  app:
    name: API-GATEWAY
    version: 1.0.0
