server.port=7368

eureka.client.enabled=true
eureka.instance.hostname=localhost
eureka.instance.prefer-ip-address=true
eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

jwt.secret=mysecretkey123456789012345678901234
jwt.access-token-ttl=900000
jwt.refresh-token-ttl=604800000

internal.token=${INTERNAL_TOKEN:qulhuwallahuahad}
user.service.url=${USER_SERVICE_URL:http://localhost:9091}
workspace.service.url=${WORKSPACE_SERVICE_URL:http://localhost:9096}
