<<<<<<< HEAD
﻿# Database Configuration
=======
# Database Configuration
>>>>>>> fbdf965a7c41b17407032ec673e13e6aef2c80ef
spring.datasource.url=jdbc:mysql://localhost:3306/ahad_services
spring.datasource.username=root
spring.datasource.password=Harun@786
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA Configuration
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

management.endpoints.web.exposure.include=*
<<<<<<< HEAD

=======
>>>>>>> fbdf965a7c41b17407032ec673e13e6aef2c80ef
